node-address {
  protocol = http
  host = localhost
  port = 9324
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = relaxed
}

queues {
  task-queue {
    defaultVisibilityTimeout = 120 seconds
  }

  task-dlq {
    defaultVisibilityTimeout = 30 seconds
  }

  email-queue {
    defaultVisibilityTimeout = 60 seconds
  }
}
